# Generated by Django 4.0.4 on 2022-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_alter_weight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_round',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10),
        ),
    ]
