# Generated by Django 4.0.4 on 2022-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0003_weight_weight_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
